# 베이스 이미지 설정
FROM ubuntu:18.04

# Nginx 설치
RUN apt-get -y update && apt-get -y upgrade 
RUN apt-get -y install nginx

# 포트 표기
EXPOSE 80

# Web 컨텐츠 배치 - 지금 바로 실행X, 다음 번째 빌드에 실행.
ONBUILD ADD website.tar /var/www/html/

# Nginx 실행.
CMD ["nginx", "-g", "daemon off;"]
